### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [fukamachi/mito-attachment#6]
Building with SBCL 2.2.7.28-02bc916fd / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id cee46a9a763d0ec6088e425844384ca908f2f2ce

*mito-attachment* fails to build with the following error:

```
Unhandled SB-INT:SIMPLE-PROGRAM-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {10016C8003}>: attempt to add the method#<STANDARD-METHOD (#<DAO-TABLE-MIXIN MITO.ATTACHMENT.MIXIN:ATTACHMENT>) {102CF969E3}>to the generic function#<STANDARD-GENERIC-FUNCTION MITO.ATTACHMENT.MIXIN:FILE-SIGNED-URL (0)>; but the method and generic function differ in whether they accept&REST or &KEY arguments.

```

[Full log here](http://report.quicklisp.org/2022-11-05/failure-report/mito-attachment.html)

**Comment by fukamachi** [comment]
Thanks. Fixed in 5022a07f667f41906ce3dced827258fed268c36d.
